name: Benchmark
on:
  workflow_dispatch:

env:
  CI: true
jobs:
  Test:
    if: github.repository == 'vnphanquang/githooks' # prevents this action from running on forks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Benchmark
        run: 'deno task bench'

